version: '3'
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    entrypoint: redis-server --appendonly no
    restart: always
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/tmp/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /tmp/data/db:/tmp/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
  jodelapp:
    image: jodel_app:latest
    container_name: "jodelapp"
    environment:
      - MONGO_HOST=mongodb
      - REDIS_HOST=redis
    ports:
        - 3000:3000
    command: npm start
    depends_on:
      - redis
      - mongodb
  abapp:
    image: ab_app:latest
    container_name: "ab"
    environment:
      - HOST=jodelapp
      - PORT=3000
    depends_on:
      - jodelapp

  